### ISSUE TITLE
GPG Signing for Maven Artifacts.

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#43]
Adding GPG Signing for Maven artifacts.

Nigel Comment
'''- pushing maven artifacts from egeria-release-1.0 to maven central (and also to our local nexus 'release' repository)
 - includes GPG signing
'''

**Comment by planetf1** [comment]
have created https://github.com/odpi/egeria/pull/823 to attempt to start the process of pushing maven release artifacts for 1.0

**Comment by planetf1** [comment]
after annotating, i noticed artifacts were available in he staging repository., but i do not know when they were put there

however these were versioned as 1.1 - which must have been from the master build (1.1-SNAPSHOT)

**Comment by planetf1** [comment]
Still no artifacts at maven central. Please advise.

**Comment by schannamallu** [comment]
I see few artifacts in nexus staging repository, are these you are looking for?
![image](https://user-images.githubusercontent.com/41459780/54146798-2522ac80-4407-11e9-9da9-7efb5cf6239b.png)

**Comment by planetf1** [comment]
I am looking for the maven artifacts in maven central ie https://mvnrepository.com/artifact/org.odpi.egeria/open-connector-framework

**Comment by planetf1** [comment]
Do we have any update on this please ? We are getting closer to creating the next release 
cc: @jmertic - it's important we get our Egeria released formalized on maven central

**Comment by schannamallu** [comment]
@planetf1, Added credentials to settings file to publish to maven central. But unable to test due to the issue  #61 . 
@jmertic @tykeal

**Comment by schannamallu** [comment]
@planetf1, Now we able to see the odpi created staging repository

![image](https://user-images.githubusercontent.com/41459780/56827202-23cd0800-682c-11e9-99ab-74ae6ae60654.png)

And I see there are some error which we need to fix.

CC: @tykeal

**Comment by planetf1** [comment]
Ok thanks. let me know if there's any help you need on the code/egeria side.

**Comment by tykeal** [comment]
@planetf1 it looks like we're missing javadoc generation on some (most?) of your artifacts. That's going to block release from staging into maven central itself. The signature validation failure is on our end. We hadn't published the public signing key to the key servers. The validation should pass as soon as they can actually get the key.

That just leaves the javadoc issue.

**Comment by planetf1** [comment]
Ah ok! Thanks. So that's javadoc failing with mvn deploy? Are the logs available? Though I should be able to reproduce. I thought they were clean so perhaps one of the recent fixes broke them,

**Comment by planetf1** [comment]
I can't test easily with mvn deploy (credentials etc). Is the build running mvn javadoc:javadoc? That is failing for me so I can investigate, but if you could provide the exact invocation that would be really useful!

Many thanks

**Comment by schannamallu** [comment]
@planetf1 
https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-sonar/225/consolehttps://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-stage-master/137/console

**Comment by schannamallu** [comment]
https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-sonar/227/console

**Comment by schannamallu** [comment]
https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-stage-master/137/console

**Comment by planetf1** [comment]
> @planetf1
> https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-sonar/225/consolehttps://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-stage-master/137/console

This is caused by the sonar build failing, which is tracked in https://github.com/odpi/ci-management/issues/61

**Comment by planetf1** [comment]
> https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-sonar/227/console

Also caused by https://github.com/odpi/ci-management/issues/61

**Comment by planetf1** [comment]
> https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-stage-master/137/console

This appears to be a build of 1.1 (which is not yet released) into the local Nexus snapshot repository.
I hadn't expected to see that yet (as we're not quite ready for a 1.1 release).

What we do need is a 
 1.0 release (from egeria-release-1.0) -> maven central
 Ongoing snapshots 1.1-SNAPSHOT (from master) 

As mentioned earlier, the root cause of the first two failures is the sonar build failing. This looks like a resource issue or failure of the sonar scan. I had a similar issue locally, and we decided it was reasonable to exclude the fvt test code from the scan -- which is mentioned in the references issue. That needs to be tried as it doesn't seem to be effective yet -- the logs are still referring to modules that should be excluded.

**Comment by planetf1** [comment]
A javadoc error was mentioned earlier - do you have any logs of that aspect failing?

**Comment by schannamallu** [comment]
@

> > https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-stage-master/137/console
> 
> This appears to be a build of 1.1 (which is not yet released) into the local Nexus snapshot repository.
> I hadn't expected to see that yet (as we're not quite ready for a 1.1 release).
> 
> What we do need is a
> 1.0 release (from egeria-release-1.0) -> maven central
> Ongoing snapshots 1.1-SNAPSHOT (from master)
> 
> As mentioned earlier, the root cause of the first two failures is the sonar build failing. This looks like a resource issue or failure of the sonar scan. I had a similar issue locally, and we decided it was reasonable to exclude the fvt test code from the scan -- which is mentioned in the references issue. That needs to be tried as it doesn't seem to be effective yet -- the logs are still referring to modules that should be excluded.

@planetf1, Artifacts Build version are based on pom files. So are you using the correct versions in the pom file? 
I am not sure we specify any version in the build job.

**Comment by planetf1** [comment]
My error. Yes we are using 1.1-SNAPSHOT

What we still need though is
 egeria-release-1.0 -> Maven Central (tagged as 1.0)
 master -> Maven Central (tagged as 1.1-SNAPSHOT)

As of now we still only have 0.1 & 0.2 - published manually - on maven central

It would also help to have clarity on where the nexus repository is published to in the process. 
I can currently see
https://nexus.odpi.org/content/repositories/snapshots/org/odpi/egeria/ - contains 0.3-SNAPSHOT (old) and 1.1-SNAPSHOT snapshots - which seems fine.
https://nexus.odpi.org/content/repositories/releases/ - nothing here
https://nexus.odpi.org/content/repositories/staging/org/odpi/egeria - contains 0.3 & 1.1 . I assume this was created automatically by the build process modifying the version number to aid testing

At some point we will want
 egeria-release-1.1 ->  Maven Central (1.1) 

but we are not yet ready for that. Given there has been some discussion it would be helpful if the process (in terms of what the egeria team need to do) was documented

**Comment by tykeal** [comment]
The build process in our environment is as follows:

* PR -> triggers a verify build. No artifacts are stored
* Merge -> triggers a merge build. Artifacts are stored to Snapshots repo
* Daily / release jobs -> Built daily (supposed to be keyword triggerable, but we have issues with that from GitHub) builds release candidate artifacts (non SNAPSHOT) and auto-opens a staging repository in Nexus.
  * If GPG signing is enabled artifacts will be auto signed
  * If Maven central is also enabled then a Maven central staging repo will be auto generated
* Upon ratification of a release by the appropriate parties and subsequent helpdesk request (issue tracker tickets are not accepted for this) LF Release Engineering (LFRE) will publish the artifacts into the releases repository the corresponding staging repository and if maven central is also in play that staging repo will be published to maven central
  * This will be modified in the future as we are moving to a self-service model where projects will be able to make a very specific type of modification to the repository to initiate a release without involving LFRE. We do not presently have the specific timeline but it should definitely be by EOQ3'2019

On the v0.1 & 0.2 released artifacts, I don't know how you got those to maven central previously, nor do I know how you actually produced them as using our workflows they should have ended up in our release repository.

Secondly, the staging URL that you pointed to is a bad one to actually reference. The reason being that if there are multiple staging repos the _oldest_ is always shown and not the newest like the SNAPSHOT system. This is a bug in Nexus 2 that Sonatype has informed us they will not fix as they are not doing any major work there except security support anymore. We have yet to move to Nexus 3 for staging workflows as the new subsystem is different enough that our current tooling breaks and we haven't had time to fix that.

**Comment by planetf1** [comment]
Our overall objectives are to
 * Have a streamlined, supported release process to push releases to maven central
 * Publish snapshots of the current release(s) under development to maven central as snapshots automatically.

To answer some of the questions
 * v0.1, v0.2 were released manually by us (the egeria dev team)
 * Thanks for the info on the staging URL (confusing! - understand) & how staging occurs

And now some new questions
 * How do we now retrospectively release the contents of egeria-release-1.0 to maven central, signed by odpi. This may not exactly follow the documented process given that the release is already effectively done? We just need to update maven central?
* Are we able to push actual SNAPSHOT releases to maven central. I am thinking this is useful for any external parties making use of egeria during their development cycle. They might need latest/master code, but can work using maven artifacts. Whilst they could be pointed at the odpi repo, maven central would be useful. They would explicitly refer to '1.1-SNAPSHOT' or similar

**Comment by planetf1** [comment]
Can we also clarify the exact process needed to be undertaken by the egeria team so that we are clear what we need to do for our next release - which will come in the next few weeks/month

With no overlapping releases
 - We raise a LF helpdesk request to promote the staging repository (above) to release status. For example in the current case this would release '1.1' straight off master
 - The product team also create a egeria-release-1.1 branch if needed, and tag a git release
 - The product team can ask for a new build process for this release if needed

However as we worked on the last release we had an overlap of a number of weeks where we froze the release concurrently with continuing development on master. We also needed to add some fixes to the release (ie think 1.1.1 for example). I'm thinking about how this is handled in the LF process

* Having a branch early (like egeria-release-1.1) allows us to stablize the code, as well as implement post-release fixes
* If we have a new branch we'd immediately need a new build process to support - though builds would be more ad/hoc/infrequent. verification of PRs would still be desirable) - this would be an issue? or a LF request?
* Based on the automatic removal of -SNAPSHOT in staging, it would make sense if once the branch was made, we updated master to the release+1 (ie 1.2-SNAPSHOT) 
* Would we also ourselves change the version in the branch from 1.1-SNAPSHOT to 1.1 ?
* When we have code to release we would do a git tag & request LF helpdesk to release the artifacts from the branch staging repo?
* For any subsequent fix versions to release (ie 1.1.1) we would repeat the previous 2 steps accordingly?

**Comment by tykeal** [comment]
> * How do we now retrospectively release the contents of egeria-release-1.0 to maven central, signed by odpi. This may not exactly follow the documented process given that the release is already effectively done? We just need to update maven central?

I really don't know how you got the previous releases pushed out there. Our processes should not allow for an artifact that was not generated on the infrastructure to be published. The best way forward for this would be to rebuild the 1.0 artifacts using the staging system and publish that.

> * Are we able to push actual SNAPSHOT releases to maven central. I am thinking this is useful for any external parties making use of egeria during their development cycle. They might need latest/master code, but can work using maven artifacts. Whilst they could be pointed at the odpi repo, maven central would be useful. They would explicitly refer to '1.1-SNAPSHOT' or similar

No, we can't publish SNAPSHOT to maven central.



> Can we also clarify the exact process needed to be undertaken by the egeria team so that we are clear what we need to do for our next release - which will come in the next few weeks/month
> 
> With no overlapping releases
> 
> * We raise a LF helpdesk request to promote the staging repository (above) to release status. For example in the current case this would release '1.1' straight off master
> * The product team also create a egeria-release-1.1 branch if needed, and tag a git release
> * The product team can ask for a new build process for this release if needed
> 
> However as we worked on the last release we had an overlap of a number of weeks where we froze the release concurrently with continuing development on master. We also needed to add some fixes to the release (ie think 1.1.1 for example). I'm thinking about how this is handled in the LF process
> 
> * Having a branch early (like egeria-release-1.1) allows us to stablize the code, as well as implement post-release fixes
> * If we have a new branch we'd immediately need a new build process to support - though builds would be more ad/hoc/infrequent. verification of PRs would still be desirable) - this would be an issue? or a LF request?

Just add additional jobs. Our job templates support a concept we call "streams" which is effectively a branch to follow. We call them streams because some of our projects use release names for their branches and it was easier to say a "stream" of work than a particular version ;)

> * Based on the automatic removal of -SNAPSHOT in staging, it would make sense if once the branch was made, we updated master to the release+1 (ie 1.2-SNAPSHOT)

We have version bumping scripts available in lftools, but in general, if you're using our release process you only really need to update one file after you've done the release tagging and such and so there isn't much need to use the script. You do, however, absolutely _need_ to update the version number!

> * Would we also ourselves change the version in the branch from 1.1-SNAPSHOT to 1.1 ?

Totally on you. This is in the POM files for Java apps and is in some other fashion encoded into your repository for other languages.

> * When we have code to release we would do a git tag & request LF helpdesk to release the artifacts from the branch staging repo?

Yes. Though we have automation that should be fully in place by end of Q32019 that will allow you to not have to open a helpdesk ticket but handle all of the release yourself, including the staging release to production of both nexus and maven central

> * For any subsequent fix versions to release (ie 1.1.1) we would repeat the previous 2 steps accordingly?

Yes.

**Comment by planetf1** [comment]
On the 1.0 release
 * The nexus repo contains 0.3-SNAPSHOT but not 1.0-SNAPSHOT (0.3 got renamed to 1.0)
 * The build process is creating a 1.0 release build at https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-clm-egeria-release-1.0/ but I see no snapshots from this
 * In the pom for this release, the version in the POM is set to 1.0
 * Given this is the correct process to a) Get snapshot builds working off this branch b) Update version to 1.0.1 or similar c) Request helpdesk to release (we can then gittag the latest release)

On snapshots
 * Thanks. We will discuss this in the team. I understand the current situation is we don't have support for snapshots on maven central, only releases, whilst snapshots can be retrieved from the 
ODPi repo

* 'just add additional streams' - Suresh perhaps you could clarify if the egeria team should do this and if not, where the request would be raised

Releasing next version
 * We will create a new branch ie egeria-release-1.1 when we want to stabilize
 * We will request a new stream be setup to build off this branch 
 * We will switch the version number in the pom from 1.1-SNAPSHOT to 1.1
 * We will test the nexus repo snapshots
 * WHen happy we will request the LF helpdesk to release, and ensure we have done a git tag
 * All of the above is concurrent with ongoing work on master.

Releasing a minor update
 * We will switch the version number in the pom from 1.1 to 1.1.1 or similar
 * We will test the nexus repo snapshots
 * WHen happy we will request the LF helpdesk to release, and ensure we have done a git tag

is that correct?
Thanks

**Comment by tykeal** [comment]
Streams are defined in your JJB file. See https://github.com/odpi/ci-management/blob/master/jjb/egeria/egeria.yaml#L10-L12 or you can do it like we do in ODL where each stream ends up as it's own project definition (see https://github.com/opendaylight/releng-builder/blob/master/jjb/odlparent/odlparent.yaml )

For releases you _never_ have to change the POM file to be a non-SNAPSHOT version. In fact, the process will break if you do this. The reason is the staging job will do a change against the POM files down the tree to remove SNAPSHOT (not just from your artifacts, but from all dependencies as well as you should never depend on a SNAPSHOT for a release version!) and then do the build. We'll store off a gitbundle that has all the needed changes and when a release happens we apply that bundle (and push it back) and tag against that. That way your tagged version matches exactly what we built against.

What this means is that all you should ever worry about is your version, and not if it's a SNAPSHOT or not, the jobs take care of the more boring and mechanical work for you.

**Comment by planetf1** [comment]
Thanks. reverting our change to go from SNAPSHOT to release & then upping the level to 1.0-SNAPSHOT. Then we can do a build and see what's in staging :-)

**Comment by planetf1** [comment]
@tykeal thanks 

In https://github.com/odpi/ci-management/blob/master/jjb/egeria/egeria.yaml#L10-L12
I think then we would want to replace
```
- project:
    name: egeria
    project-name: odpi-egeria
    project: egeria
    mvn-settings: egeria-settings
    archive-artifacts: ''
    build-node: centos7-builder-2c-1g
    cron: 'H 11 * * *'
    stream:
      - 'master':
          branch: master
    jobs:
      - github-maven-clm
      - github-maven-merge
      - github-maven-stage
      - github-maven-verify:
          mvn-goals: 'clean deploy -DskipFVT'
    sign-artifacts: true
    mvn-central: '{mvn_central}'
    ossrh-profile-id: '{ossrh_profile_id}'
```
with
```
- project:
    name: egeria
    project-name: odpi-egeria
    project: egeria
    mvn-settings: egeria-settings
    archive-artifacts: ''
    build-node: centos7-builder-2c-1g
    cron: 'H 11 * * *'
    stream:
      - 'master':
          branch: master
      - 'release 1.0':
          branch: egeria-release-1.0
    jobs:
      - github-maven-clm
      - github-maven-merge
      - github-maven-stage
      - github-maven-verify:
          mvn-goals: 'clean deploy -DskipFVT'
    sign-artifacts: true
    mvn-central: '{mvn_central}'
    ossrh-profile-id: '{ossrh_profile_id}'
```
Assuming we're ok with the schedule, build parms etc. This would mirror what we have for master with release 1.0 ? (and we can add release 1.1, 1.2 etc as we create new branches and go through the release cycle?)

I assume I would also delete
```
- project:
    name: 'egeria-maven-clm'
    project-name: 'odpi-egeria'
    project: egeria
    mvn-settings: egeria-settings
    build-node: centos7-builder-4c-4g
    cron: '@daily'
    mvn-opts: '-Xmx2048m'
    jobs:
      - github-maven-clm
    stream:
      - 'egeria-release-1.0':
          branch: 'egeria-release-1.0'
```
Since that only builds the CLM component for 1.0 - though it's an example of adding a new project if we needed quite different setup for a new release

Finally I wasn't quite clear what release egeria-sonar would run on as it's defined as 
```
- project:
    name: egeria-sonar
    project-name: odpi-egeria
    project: egeria
    mvn-settings: egeria-settings
    archive-artifacts: ''
    build-node: centos7-builder-4c-4g
    cron: '@daily'
    mvn-opts: '-Xmx2048m'
    jobs:
      - github-maven-sonar

    sonarcloud: true
    sonarcloud-project-organization: '{sonarcloud_project_organization}'
    sonarcloud-project-key: odpi_egeria
    sonarcloud-api-token: '{sonarcloud_api_token}'
```

Since it refers to project 'egeria' does it just run against all of the streams above under the egeria project?

I'd appreciate any comments on whether I've got this right - I'm happy to code up the PR to make the change. It will be useful if we know how to do this in future

Thanks
cc: @schannamallu

**Comment by planetf1** [comment]
In addition, what needs to be done in terms of the project settings in the github repo for that branch (I don't have access currently) - presumably a copy of the branch protection rules?

**Comment by schannamallu** [comment]
@planetf1, Yes. Looks like valid cases and these are related to the discrepancies you mentioned in the RT.
I already started working on them. I will add this changes and test them.

CC: @tykeal

**Comment by tykeal** [comment]
@planetf1 Sonar jobs only run on master per our current definition. The reason being our projects have generally found the following to be true:

1. Sonar on new developed code is more useful than on maintained code
1. Sonar, in general, has problems with branches, though it's possible to work around
1. The Sonar job by default only runs once a week, in our Gerrit systems it can be triggered with a comment keyword, but those don't work properly on merged GitHub changes, but _should_ work on open GitHub changes (keyword is run-sonar)

To your other questions. Yes, the standalone egeria-maven-clm should be removed, and the mvn-opts that it has defined should be moved up to the primary egeria section. I'm actually surprised we haven't been getting failures to verify the JJB since that should be creating a name collision with the primary egeria section

**Comment by planetf1** [comment]
I did seperately notice that the jjb deploy is failing at https://jenkins.odpi.org/view/ci-management/job/ci-management-jjb-deploy-job/lastBuild/console - and raised a helpdesk case.

The comments are helpful. Thanks

**Comment by planetf1** [comment]
Thanks @schannamallu if you're part way through best you finish then. If there were other changes needed elsewhere I'll be interested in knowing so we can perhaps help out by raising a PR next time.

I have an egeria-release-1.0 PR ready to verify once things are in place

**Comment by planetf1** [comment]
As per https://github.com/odpi/ci-management/issues/90 we still need clarification on the modifications made to strings like 1.0-SNAPSHOT during the build

Can you point to the source for these scripts. I did search on github but found scripts that seemed to change all files not just *.xml, but I may well have been looking at the wrong scripts.

We need either no change or a complete change as we have cross references within our build to those version numbers - including in documentations, samples, scripts .. and not just in poms

**Comment by tykeal** [comment]
This script that does the change only works on *.xml files. The one in question is:

https://github.com/lfit/releng-global-jjb/blob/master/shell/maven-patch-release.sh

We only touch *.xml as we're specifically modifying the files that control the build, we won't touch doc changes.

To be specific, the staging template uses this build definition:

https://github.com/lfit/releng-global-jjb/blob/master/jjb/lf-maven-jobs.yaml#L874-L905

**Comment by planetf1** [comment]
Ok, thanks for those specifics. I'll review all of our snapshot references and figure out if we can work with just the pom changes

**Comment by schannamallu** [comment]
@planetf1 , Implemented above mentioned comments.
Can you check it and will close this issue.

**Comment by planetf1** [comment]
I went to followup to get the 1.0 build fixed to be able to publish.

However I notice the builds are failing as it appears the images aren't setup correctly:
https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-stage-egeria-release-1.0/lastBuild/console

Then for this build it appears the destination directory for upload is read only
https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-merge-egeria-release-1.0/lastBuild/console

**Comment by planetf1** [comment]
I see a new build ran this morning as scheduled, but failed with problems unpacking the UI

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project access-services-user-interface: Could not extract the Node archive: Could not extract archive: '/tmp/r/com/github/eirslett/node/10.12.0/node-10.12.0-linux-x64.tar.gz': EOFException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project access-services-user-interface: Could not extract the Node archive: Could not extract archive: '/tmp/r/com/github/eirslett/node/10.12.0/node-10.12.0-linux-x64.tar.gz'

Did we run out of some resource this time? Disk space perhaps? network connectivity?

**Comment by schannamallu** [comment]
@planetf1 ,
seems like network issue, the first job build is success , i mean  its like resource/network related issues.
i am going to rerun the job and check the status.

**Comment by schannamallu** [comment]
@planetf1 ,
 Getting error while push artifacts to nexus : maven merge release1.0 

```
Uploading org/odpi/egeria/access-services-connectors/1.0/access-services-connectors-1.0.jar
Uploading org/odpi/egeria/connector-configuration-factory/1.0/connector-configuration-factory-1.0.pom.md5
ERROR: Repository is read only
```
we are sending 1.0 version to sanpshot repo . 

> I went to followup to get the 1.0 build fixed to be able to publish.
> 
> However I notice the builds are failing as it appears the images aren't setup correctly:
> https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-stage-egeria-release-1.0/lastBuild/console
> 
> Then for this build it appears the destination directory for upload is read only
> https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-merge-egeria-release-1.0/lastBuild/console
odpi-egeria-maven-stage-egeria-release-1.0

**Comment by schannamallu** [comment]
@planetf1  odpi-egeria-maven-stage-egeria-release-1.0   build now success.

https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-merge-egeria-release-1.0/4/console
https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-verify-egeria-release-1.0-mvn35-openjdk8/1/console

**Comment by planetf1** [comment]
Super. I've reviewed the results.
 - The maven artifacts look correctly versioned
 - The source doesn't seem to include bad references to 1.0-SNAPSHOT
 - The built assemblies are similar to our current master (albeit subject to https://github.com/odpi/egeria/issues/1109 )

As such I think we are ready to sign and release to MC. In many respects this is a test in any case. As the 1.0 build is so late no-one will be usefully using it. So this is extra validation prior to us building 1.1 (which will likely be in a matter of weeks).

I will raise a helpdesk issue to release the artifacts.

**Comment by planetf1** [comment]
Whilst maven-merge and maven verify have build ok, maven-stage has not.

Is maven-stage needed for the artifacts to be published to maven central?
If so -> can you take a look/fix?
Then -> either let me know I should raise a helpdesk request to release the 1.0 artifacts from this build to maven central, or can you do so?

Many thanks

**Comment by schannamallu** [comment]
@planetf1 ,
maven-stage pipeline has script called [maven-patch-release.sh](https://github.com/lfit/releng-global-jjb/blob/master/shell/maven-patch-release.sh)

this script will place the -SNAPSHOT with  <null> in all *.xml files and commit changes
but release1.0 branch has no -SNAPSHOT , when it trying to commit  the git write as below
```
nothing to commit, working tree clean
Build step 'Execute shell' marked build as failure
```
in the pipeline when shell watch  "nothing to commit"  the default  behaviour  of shell is to fails the pipeline.
https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-stage-egeria-release-1.0/4/console

Please let me know how can we proceed

**Comment by planetf1** [comment]
My bad. I've now merged the change I made a week or so which I hadnt merged due to the unknown build state.

The verify build should be started now. If that works it would be great if you could retry the other build

**Comment by schannamallu** [comment]
@planetf1 ,
The CLM job fail because egeria code has bugs which are having CVE rating more than 7 . I think developers should fix the vul-bugs. The rating more than 7 make the build fail

![Screen Shot 2019-06-06 at 9 11 00 AM](https://user-images.githubusercontent.com/41459780/59035390-2ebb8500-883b-11e9-82b8-12ca6344c2ae.png)

**Comment by planetf1** [comment]
Yes thanks - this is intentional. We are working through deciding what rules to go with and what process to put around the scans. I have added some new rules to demonstrate the capabilities for our review discussions. We'll tweak them over the coming days & consider notifications etc.

If the current rules cause a process problem I can lower the severity.

We're ok to go with shipping despite the CLM failure (technically it was already).
Thanks

**Comment by schannamallu** [comment]
@planetf1 

the builds are successful now.
--merge
--stage
for master and release1.0.. please can you check

**Comment by planetf1** [comment]
Thanks. The builds look good so far, but I'll check the artifacts in more detail tomorrow. many thanks

**Comment by planetf1** [comment]
I can now see artifacts uploaded to the maven staging repository. 
Maven is reporting some warnings which we will now address in the egeria dev team. (javadoc validation & sources validation)

I'll get back here when that is done.

**Comment by planetf1** [comment]
I've made the required changes to egeria.... but my last 2 PR builds have failed due to the javadoc plugin running out of heap when building the igc docs.

I've gone from default to 512m

I'm giving it one final go at 1536m (if this is effective). If this still doesn't work I'm going to need some help to debug/understand the environment better. I do NOT get failures on my local mac environment. See https://jenkins.odpi.org/job/odpi-egeria-maven-verify-egeria-release-1.0-mvn35-openjdk8/5/

The other option will be to prevent the complete javadoc processing to avoid so much heap being needed. If there's no other ideas I'll try this

**Comment by schannamallu** [comment]
@planetf1  the job success
https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-verify-egeria-release-1.0-mvn35-openjdk8/8/console

**Comment by planetf1** [comment]
I made some further changes to clear up the javadoc issues, and meet the requirement for javadoc and sources jar imposed by sonatype.

Can we try the staging again? I need to see if sonatype now pass the artifacts

**Comment by planetf1** [comment]
The staging build worked.
I corrected the issues with javadoc/source, 
the new staging build ran
I checked on maven central
I was able to release the artifacts to the maven central repo

I think we can therefore close this issue?

**Comment by schannamallu** [comment]
@planetf1  Thank you !   Closing this issue
