### ISSUE TITLE
Build times - 25 mins plus

### ISSUE THREAD

**Issue by planetf1** [odpi/ci-management#74]
Our builds are currently taking around 25 minutes
 - https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-verify-master-mvn35-openjdk8/buildTimeTrend

When we build locally ie on MacOS builds are taking more like 9-11 minutes. Linux is similar
Windows is more like 30, but that is expected (I/O/API)

Are we running into resource constraints that are making the builds slower than they could be?

We do have some areas - like some FVT tests which we could skip/refactor -- that's down to the project - but is there anything on the infrastructure side that needs looking at? Is there memory constrant for example on the vms or containers?

**Comment by tykeal** [comment]
Are those timings that you're citing against clean cache builds? Our CI design is always clean cache. There's some additional time that is tacked onto builds in the CI system for log and stats gathering and storage.

**Comment by planetf1** [comment]
No, My MacOS figures were with a populated ~/.m2. The official builds do take longer, and are clean each time (as you say - the correct approach for official builds). But if there's any obvious improvement, worth considering. 25 mins did seem quite a lot longer than 10. - even the core maven part takes about double.

**Comment by tykeal** [comment]
I'll admit that I would love to for us to be able to reduce build times. But we've found, time and again that not doing all builds against clean cache ends up having bugs creep into the code base that are only exposed with a clean cache.

It's our general reason as to why we run all builds that way and all builds happen on a single use instance, so it's harder to share cache even if we wanted to!

Since the source of this appears to have been comparing against a populated and unpopulated cache situation I'm going to close the issue.
